import type { DateValue, FieldDefinition } from '../../shared/platform';
import { unknownDate } from '../../shared/platform';
import { DateTime, Field, Select } from './common';
import { ContentPicker, MediaPicker } from './pickers';

type Row = Record<string, any>;
function RepeatRows({ value, onChange, create, render, label }: { value: Row[]; onChange: (rows: Row[]) => void; create: () => Row; render: (row: Row, update: (key: string, value: unknown) => void) => React.ReactNode; label: string }) {
  const rows = value ?? [];
  const move = (index: number, delta: number) => { const next = [...rows]; [next[index], next[index + delta]] = [next[index + delta], next[index]]; onChange(next.map((row, i) => 'sortOrder' in row ? { ...row, sortOrder: i } : row)); };
  return <div className="repeat">{rows.map((row, index) => <fieldset key={row.id ?? index}><legend>{label} {index + 1}</legend><div className="form-grid">{render(row, (key, v) => onChange(rows.map((item, i) => i === index ? { ...item, [key]: v } : item)))}</div><div className="row-actions"><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>上移</button><button type="button" disabled={index === rows.length - 1} onClick={() => move(index, 1)}>下移</button><button type="button" className="danger quiet" onClick={() => onChange(rows.filter((_, i) => i !== index))}>移除此项</button></div></fieldset>)}<button type="button" onClick={() => onChange([...rows, create()])}>＋ 添加{label}</button></div>;
}

export function DetailField({ definition: f, value, onChange }: { definition: FieldDefinition; value: any; onChange: (value: any) => void }) {
  if (f.type === 'deadline') {
    const date: DateValue = value ?? unknownDate();
    return <fieldset className="field wide"><legend>{f.label}</legend><div className="form-grid"><Field label="时间精度"><select value={date.precision} onChange={e => onChange({ ...date, precision: e.target.value, date: null, at: null })}><option value="unknown">待公布 / 待核实</option><option value="date">仅日期</option><option value="datetime">具体时刻</option></select></Field>{date.precision === 'date' && <Field label="日期"><input type="date" value={date.date ?? ''} onChange={e => onChange({ ...date, date: e.target.value || null })}/></Field>}{date.precision === 'datetime' && <Field label="具体时刻（北京时间 UTC+8）"><DateTime value={date.at} onChange={at => onChange({ ...date, at })}/></Field>}<Field label="对外显示时区"><input value={date.timeZone} onChange={e => onChange({ ...date, timeZone: e.target.value })} placeholder="Asia/Shanghai"/></Field></div><small>未知时间保持为空；只有日期时不产生秒级倒计时。报名、内部材料、作品提交截止分别维护。</small></fieldset>;
  }
  if (f.type === 'positions') return <fieldset className="wide"><legend>{f.label}</legend><RepeatRows value={value} onChange={onChange} label="岗位" create={() => ({ id: crypto.randomUUID(), title: '', description: '', capacity: 1, enabled: true, sortOrder: value?.length ?? 0 })} render={(row, update) => <><Field label="岗位名称"><input value={row.title} maxLength={120} onChange={e => update('title', e.target.value)}/></Field><Field label="岗位总名额"><input type="number" min="1" max="10000" value={row.capacity} onChange={e => update('capacity', Number(e.target.value))}/></Field><Field label="岗位说明" wide><textarea value={row.description} onChange={e => update('description', e.target.value)}/></Field><label className="check"><input type="checkbox" checked={row.enabled} onChange={e => update('enabled', e.target.checked)}/>开放此岗位</label></>}/><small>已存在申请的岗位由服务器保护。名额包括现有成员，不会通过前端按钮绕过并发校验。</small></fieldset>;
  if (f.type === 'steps') return <fieldset className="wide"><legend>{f.label}</legend><RepeatRows value={value} onChange={onChange} label="步骤" create={() => ({ id: crypto.randomUUID(), title: '', body: '', resourceIds: [], sortOrder: value?.length ?? 0 })} render={(row, update) => <><Field label="步骤名称" wide><input value={row.title} maxLength={200} onChange={e => update('title', e.target.value)}/></Field><Field label="学习说明" wide><textarea value={row.body} rows={4} onChange={e => update('body', e.target.value)}/></Field><div className="field wide"><span>关联学习资料</span><ContentPicker kind="resources" value={row.resourceIds} onChange={ids => update('resourceIds', ids)}/></div></>}/></fieldset>;
  if (f.type === 'authors') return <fieldset className="wide"><legend>{f.label}</legend><RepeatRows value={value} onChange={onChange} label="作者" create={() => ({ userId: null, name: '' })} render={(row, update) => <><Field label="公开署名"><input value={row.name} maxLength={100} onChange={e => update('name', e.target.value)}/></Field><Field label="关联用户 ID（可选）" hint="只关联真实账号；不会公开邮箱等联系方式。"><input value={row.userId ?? ''} placeholder="可留空" onChange={e => update('userId', e.target.value || null)}/></Field></>}/></fieldset>;
  if (f.type === 'awards') return <fieldset className="wide"><legend>{f.label}</legend><RepeatRows value={value} onChange={onChange} label="获奖依据" create={() => ({ title: '', evidenceUrl: '' })} render={(row, update) => <><Field label="奖项名称"><input value={row.title} maxLength={200} onChange={e => update('title', e.target.value)}/></Field><Field label="依据链接（必填）"><input type="url" value={row.evidenceUrl} onChange={e => update('evidenceUrl', e.target.value)}/></Field></>}/><small>没有真实依据请不添加奖项。</small></fieldset>;
  if (f.type === 'media') return <div className="field wide"><span>{f.label}</span><MediaPicker images={f.key === 'imageIds'} value={value ?? []} onChange={onChange}/></div>;
  if (f.type === 'content') return <div className="field wide"><span>{f.label}</span><ContentPicker value={Array.isArray(value) ? value : value ? [value] : []} single={f.key === 'projectId'} kind={f.key === 'projectId' ? 'projects' : undefined} onChange={ids => onChange(f.key === 'projectId' ? ids[0] ?? null : ids)}/></div>;
  if (f.type === 'boolean') return <label className="check"><input type="checkbox" checked={!!value} onChange={e => onChange(e.target.checked)}/>{f.label}</label>;
  return <Field label={f.label} wide={f.type === 'textarea'} hint={f.type === 'datetime' ? '输入北京时间（UTC+8）；空值表示未设定。' : f.type === 'strings' ? '多项以中文或英文逗号分隔。' : undefined}>{f.type === 'textarea' ? <textarea rows={4} value={value ?? ''} onChange={e => onChange(e.target.value)}/> : f.type === 'select' ? <Select value={value ?? ''} options={f.options ?? []} onChange={onChange}/> : f.type === 'datetime' ? <DateTime value={value} onChange={onChange}/> : f.type === 'strings' ? <input defaultValue={(value ?? []).join('，')} onChange={e => onChange(e.target.value.split(/[,，]/).map((v: string) => v.trim()).filter(Boolean))}/> : <input type={f.type === 'number' ? 'number' : f.type === 'url' ? 'url' : 'text'} value={value ?? ''} onChange={e => onChange(f.type === 'number' ? e.target.value === '' ? null : Number(e.target.value) : e.target.value)}/>}</Field>;
}
