import { useEffect, useState } from 'react';
import { contentLabels, routeKeys, siteSettingsSchema, visualPresets, type MediaDTO, type SiteSettings } from '../../shared/platform';
import { api, message, query } from './api';
import { Field, Notice, Pager, when } from './common';
export { Users } from './users';
export { BusinessManager } from './business';

const routeLabels: Record<string, string> = { ...contentLabels, learning: '学习中心', core: '社团介绍 / IXD CORE', account: '个人中心' };
const presetLabels: Record<string, string> = { 'neural-cluster':'神经星簇', 'binary-mechanism':'双星机构', 'echo-nebula':'回声星云', 'asymmetric-arms':'非对称旋臂', 'spatial-gate':'空间星门', 'lattice-satellites':'晶格卫星', 'ixd-core':'IXD 核心', 'protostar-shell':'原恒星壳', 'ascent-comet':'上升彗星', 'exchange-stars':'交汇双星', 'prism-shards':'棱镜碎片', 'open-beacon':'开放信标' };

export function Overview({ navigate }: { navigate: (route: string) => void }) {
  const [data, setData] = useState<Record<string, any> | null>(null), [error, setError] = useState('');
  const load = async () => { try { setData((await api<Record<string, any>>('/admin/overview')).data); setError(''); } catch (e) { setError(message(e)); } };
  useEffect(() => { void load(); }, []);
  return <><div className="page-heading"><div><h1>管理总览</h1><p>当前账号权限范围内的内容与协作概况。</p></div><button onClick={() => void load()}>刷新</button></div><Notice error={error}/>{data && <div className="stats">{Object.entries(data).filter(([, v]) => typeof v === 'number').map(([key, value]) => <div className="stat" key={key}>{({ users:'注册用户', contents:'内容总数', published:'已发布', drafts:'草稿', pendingApplications:'待处理申请', pendingWorks:'待审核作品', registrations:'有效报名', media:'媒体附件', notifications:'通知', tasks:'待处理任务', scheduled:'定时发布' } as Record<string, string>)[key] ?? key}<strong>{value}</strong></div>)}</div>}{data?.counts && <div className="stats">{Object.entries(data.counts as Record<string, number>).map(([kind, count]) => <div className="stat" key={kind}>{contentLabels[kind as keyof typeof contentLabels] ?? kind}<strong>{count}</strong></div>)}</div>}<section className="panel"><h2>日常内容工作</h2><p>新建内容后先保存草稿并预览，确认标题、范围、附件和日期，再发布。编辑已发布内容时，保存草稿不会立即改变前台。</p><div className="button-row"><button onClick={() => navigate('contents/announcements')}>公告管理</button><button onClick={() => navigate('contents/works')}>作品审核</button><button onClick={() => navigate('applications')}>申请处理</button></div></section><section className="panel"><h2>数据与操作边界</h2><p>内容、账号、收藏、申请和报名由服务端数据库管理。公开网站只展示已发布且有权限读取的版本。</p><p>成员身份与编辑权限分开。活动报名不包含签到、考勤或签到码。开发示例请保留明确标识。</p></section></>;
}

interface SettingsDTO { revision: number; payload: SiteSettings; publishedPayload: SiteSettings | null }
export function SiteSettingsEditor({ onDirty }: { onDirty: (dirty: boolean) => void }) {
  const [doc, setDoc] = useState<SettingsDTO | null>(null), [payload, setPayload] = useState<SiteSettings | null>(null), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const load = async () => { try { const { data } = await api<SettingsDTO>('/admin/site-settings'); setDoc(data); setPayload(data.payload); setDirty(false); onDirty(false); setError(''); } catch (e) { setError(message(e)); } };
  useEffect(() => { void load(); return () => onDirty(false); }, []);
  const update = (value: SiteSettings) => { setPayload(value); setDirty(true); onDirty(true); setSuccess(''); };
  const save = async (publish: boolean) => { if (!doc || !payload) return; if (publish && !confirm('确认发布站点文案与节点设置？隐藏栏目入口不会删除内容，也不替代内容可见范围权限。')) return; setBusy(true); setError(''); setSuccess(''); try {
    const parsed = siteSettingsSchema.parse(payload); let current = doc;
    if (dirty) current = (await api<SettingsDTO>('/admin/site-settings', { method: 'PATCH', body: { expectedRevision: doc.revision, payload: parsed } })).data;
    if (publish) { await api('/admin/site-settings/publish', { method: 'POST', body: { expectedRevision: current.revision } }); current = (await api<SettingsDTO>('/admin/site-settings')).data; }
    setDoc(current); setPayload(current.payload); setDirty(false); onDirty(false); setSuccess(publish ? '站点设置已发布，前台下次刷新运营内容时生效。' : '草稿已保存，前台设置保持不变。');
  } catch (e: any) { setError(e.issues?.map((x: any) => `${x.path.join('.')}：${x.message}`).join('\n') ?? message(e)); } finally { setBusy(false); } };
  return <><div className="page-heading"><div><h1>站点内容设置</h1><p>维护运营文案和已经实现的节点。视觉算法及代码路由不可在后台执行或自定义。</p></div><div className="actions"><button disabled={busy || !dirty} onClick={() => void save(false)}>保存草稿</button><button className="primary" disabled={busy || !doc} onClick={() => void save(true)}>发布设置</button></div></div><Notice error={error} success={success}/>{error && <button onClick={() => { if (!dirty || confirm('重新读取会放弃未保存输入，确认继续？')) void load(); }}>重新读取</button>}{payload && <fieldset disabled={busy} className="panel"><legend>运营内容 · 版本 {doc?.revision}{dirty ? ' · 未保存' : ''}</legend><div className="form-grid"><Field label="网站名称"><input value={payload.siteName} maxLength={80} onChange={e => update({ ...payload, siteName: e.target.value })}/></Field><Field label="网站标语"><input value={payload.tagline} maxLength={200} onChange={e => update({ ...payload, tagline: e.target.value })}/></Field><Field label="对外联系方式与说明" wide><textarea value={payload.contact} maxLength={2000} onChange={e => update({ ...payload, contact: e.target.value })}/></Field></div><h2 className="spaced">栏目与功能节点</h2>{routeKeys.map(key => { const node = payload.nodes.find(item => item.routeKey === key)!; const changeNode = (prop: string, value: unknown) => update({ ...payload, nodes: payload.nodes.map(item => item.routeKey === key ? { ...item, [prop]: value } : item) }); return <fieldset className="grant-row" key={key}><legend>{routeLabels[key]}</legend><div className="form-grid"><Field label="节点名称"><input value={node.title} maxLength={40} onChange={e => changeNode('title', e.target.value)}/></Field><Field label="节点副标题"><input value={node.subtitle} maxLength={100} onChange={e => changeNode('subtitle', e.target.value)}/></Field><Field label="视觉预设"><select value={node.visualPreset} onChange={e => changeNode('visualPreset', e.target.value)}>{visualPresets.map(preset => <option key={preset} value={preset}>{presetLabels[preset]}</option>)}</select></Field><label className="check"><input type="checkbox" checked={node.enabled} disabled={key === 'core' || key === 'account'} onChange={e => changeNode('enabled', e.target.checked)}/>启用栏目{(key === 'core' || key === 'account') && '（必要入口）'}</label><Field label="栏目说明" wide><textarea maxLength={500} value={payload.sectionDescriptions[key]} onChange={e => update({ ...payload, sectionDescriptions: { ...payload.sectionDescriptions, [key]: e.target.value } })}/></Field></div></fieldset>; })}</fieldset>}</>;
}

interface MediaReference { contentId?: string; id?: string; title?: string; revision?: number; kind?: string }
export function MediaLibrary() {
  const [items, setItems] = useState<MediaDTO[]>([]), [q, setQ] = useState(''), [search, setSearch] = useState(''), [access, setAccess] = useState(''), [uploadAccess, setUploadAccess] = useState('PUBLIC'), [page, setPage] = useState(1), [total, setTotal] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(''), [references, setReferences] = useState<{ item: MediaDTO; rows: MediaReference[] } | null>(null);
  const load = async () => { try { const result = await api<MediaDTO[]>(`/admin/media?${query({ page, pageSize: 20, q: search, accessLevel: access })}`); setItems(result.data); setTotal(result.meta?.total ?? result.data.length); setError(''); } catch (e) { setError(message(e)); } };
  useEffect(() => { void load(); }, [page, search, access]);
  const upload = async (file?: File) => { if (!file) return; setBusy(true); setError(''); setSuccess(''); try { const body = new FormData(); body.append('accessLevel', uploadAccess); body.append('file', file); await api('/media', { method: 'POST', body }); setSuccess('文件已保存到持久化目录。可在内容编辑页选择它，替换引用后保存并重新发布。'); await load(); } catch (e) { setError(message(e)); } finally { setBusy(false); } };
  const remove = async (item: MediaDTO) => { if (!confirm(`确认删除「${item.originalName}」？此操作不可恢复；任何内容版本仍引用它时，服务器会阻止删除。`)) return; setBusy(true); try { await api(`/admin/media/${item.id}`, { method: 'DELETE' }); setSuccess('附件已删除。'); await load(); } catch (e) { setError(message(e)); } finally { setBusy(false); } };
  return <><div className="page-heading"><div><h1>媒体附件</h1><p>上传、检查引用、下载与删除。文件名由服务器生成；受限附件下载需通过权限检查。</p></div></div><Notice error={error} success={success}/><section className="panel"><h2>上传素材</h2><div className="upload-line"><select aria-label="新附件访问范围" value={uploadAccess} onChange={e => setUploadAccess(e.target.value)}><option value="PUBLIC">公开素材</option><option value="PRIVATE">受限附件</option></select><input type="file" aria-label="选择上传文件" disabled={busy} accept="image/png,image/jpeg,image/webp,application/pdf,text/plain" onChange={e => { void upload(e.target.files?.[0]); e.target.value = ''; }}/>{busy && <span>正在处理…</span>}</div><small>支持 PNG、JPEG、WebP、PDF 和纯文本。大小与实际内容由服务端校验。替换文件时先上传新文件，再到对应内容页替换引用；不直接覆盖历史附件。</small></section><form className="toolbar panel" onSubmit={e => { e.preventDefault(); setSearch(q); setPage(1); }}><input placeholder="搜索文件名" aria-label="搜索媒体" value={q} onChange={e => setQ(e.target.value)}/><button>搜索</button><select aria-label="附件范围过滤" value={access} onChange={e => { setAccess(e.target.value); setPage(1); }}><option value="">全部范围</option><option value="PUBLIC">公开</option><option value="PRIVATE">受限</option></select><button type="button" onClick={() => void load()}>刷新</button></form><div className="panel table-wrap"><table><thead><tr><th>文件</th><th>范围 / 类型</th><th>大小</th><th>引用</th><th>上传时间</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><a href={item.url} target="_blank" rel="noreferrer">{item.originalName}</a></td><td>{item.accessLevel === 'PUBLIC' ? '公开素材' : '受限附件'}<small className="block">{item.mimeType}</small></td><td>{Math.ceil(item.byteSize / 1024)} KB</td><td>{item.referenceCount}</td><td>{when(item.createdAt)}</td><td><div className="actions wrap"><button onClick={async () => { try { const { data } = await api<MediaReference[]>(`/admin/media/${item.id}/references`); setReferences({ item, rows: data }); } catch (e) { setError(message(e)); } }}>查看引用</button><button disabled={busy || item.referenceCount > 0} className="danger" onClick={() => void remove(item)}>删除</button></div></td></tr>)}</tbody></table>{!items.length && <div className="empty">暂无文件。</div>}</div><Pager page={page} total={total} onChange={setPage}/>{references && <div className="modal-backdrop"><section className="modal panel" role="dialog" aria-modal="true" aria-label="附件引用"><div className="page-heading"><h2>{references.item.originalName} 的引用</h2><button onClick={() => setReferences(null)}>关闭</button></div>{references.rows.length ? <ul>{references.rows.map((row, i) => <li key={i}>{row.title ?? row.contentId ?? row.id} {row.revision ? `（版本 ${row.revision}）` : ''}</li>)}</ul> : <p>此附件暂无内容引用。</p>}<p className="muted">历史发布版本也会保留引用，防止读者打开失效附件。</p></section></div>}</>;
}

export function AuditLog() {
  const [items, setItems] = useState<any[]>([]), [page, setPage] = useState(1), [total, setTotal] = useState(0), [q, setQ] = useState(''), [search, setSearch] = useState(''), [error, setError] = useState('');
  const load = async () => { try { const result = await api<any[]>(`/admin/audit?${query({ page, pageSize: 20, q: search })}`); setItems(result.data); setTotal(result.meta?.total ?? result.data.length); setError(''); } catch (e) { setError(message(e)); } };
  useEffect(() => { void load(); }, [page, search]);
  return <><div className="page-heading"><div><h1>操作日志</h1><p>记录操作人、时间、动作和资源。日志不可通过后台编辑；不记录密码或完整敏感载荷。</p></div></div><Notice error={error}/><form className="toolbar panel" onSubmit={e => { e.preventDefault(); setSearch(q); setPage(1); }}><input aria-label="搜索日志" placeholder="搜索动作或资源" value={q} onChange={e => setQ(e.target.value)}/><button>搜索</button><button type="button" onClick={() => void load()}>刷新</button></form><div className="panel table-wrap"><table><thead><tr><th>时间</th><th>操作人</th><th>动作</th><th>资源</th><th>摘要</th></tr></thead><tbody>{items.map(row => <tr key={row.id}><td>{when(row.createdAt)}</td><td>{row.actor?.displayName ?? row.actorName ?? row.actorId ?? '系统'}</td><td>{row.action}</td><td>{row.resourceType ?? row.targetType}<small className="block">{row.resourceId ?? row.targetId}</small></td><td><details><summary>查看记录</summary><pre className="audit-data">{JSON.stringify(row.changes ?? {}, null, 2)}</pre></details></td></tr>)}</tbody></table>{!items.length && <div className="empty">暂无日志记录。</div>}</div><Pager page={page} total={total} onChange={setPage}/></>;
}
